INCLUDE_PATH    := ./ ../external/include/ ../common/ ../gl_util/
SOURCE_PATH     := ./ ../common/ ../gl_util/
DEPENDENCY_PATH := dep
OBJECT_PATH     := obj

EXTERNAL_LIBS := $(wildcard ../external/lib/*.dylib)
LDLIBS := -lm -lpthread -lglut -framework OpenGL


CFLAGS += -O3

include ../makefile.mk
